CREATE DATABASE TEST

USE TEST

CREATE TABLE STUDENT(
	RNO INT primary key,
	NAME VARCHAR(50),
	AGE INT NOT NULL
);

INSERT INTO STUDENT VALUES(1,'vibhu',18);
INSERT INTO STUDENT VALUES(2,'SHIHORA',19);

SELECT * FROM STUDENT;

DROP DATABASE TEST ;